### ISSUE TITLE
Issue with bower install

### ISSUE THREAD

**Issue by chinnichaitanya** [heyflock/angular-bootstrap-material#13]
With the command, `bower install --save git@github.com:heyflock/angular-bootstrap-material.git#master`, I'm getting the following error,

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Am I missing something?

**Comment by adeolonoh** [comment]
@chinnichaitanya can you try `bower install --save git@github.com:teamjell/angular-bootstrap-material.git#master` instead? We moved our github account to `teamjell` and neglected to update the README.
